[package]
name = "rosl"
version = "0.1.0"
edition = "2021"

[dependencies]
dbus = "0.9.7"
zbus = {version = "4.4.0", default-features = false, features = ["tokio"]}
tokio = {version = "1.39.3", features = ["full"]}
tracing = "0.1.40"
